In [1]:
import numpy as np
seed_array = [2,3,4,5,6,7] # Intializing the seed array or seed vector
vandermonde_matrix = np.vander(seed_array,increasing=False) #Creating the vandermonde matrix from the seed array or vector
print(vandermonde_matrix)


[[   32    16     8     4     2     1]
 [  243    81    27     9     3     1]
 [ 1024   256    64    16     4     1]
 [ 3125   625   125    25     5     1]
 [ 7776  1296   216    36     6     1]
 [16807  2401   343    49     7     1]]
